<?php
/**
 * @file
 *    pinboard.module - a simple bookmarking utility and UI
 */

/**
 *  Load the common includes
 */
function pinboard_load_common_includes() {
  static $pinboard_module_path;
  if (!$pinboard_module_path) {
    $pinboard_module_path = drupal_get_path('module', 'pinboard');
    require_once($pinboard_module_path .'/pinboard.common.inc');
  }
}

pinboard_load_common_includes();

/**
 * Implementation of hook_init()
 * Adds the pinboard JavaScript and CSS
 */
function pinboard_init() {
  drupal_add_js(drupal_get_path('module', 'pinboard'). '/theme/pinboard.js');
  drupal_add_css(drupal_get_path('module', 'pinboard'). '/theme/pinboard.css');
}

/**
 * Implementation of hook_views_api()
 */
function pinboard_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'pinboard') .'/views',
  );
}

/**
 *  Implementation of hook_perm()
 */
function pinboard_perm() {
  return array(
    'view public bookmarks', // public bookmarks
    'create bookmarks',
    'delete own bookmarks',
    'delete any bookmarks'
  );
}


/**
 *  Implementation of hook_menu()
 */
function pinboard_menu() {
  $items = array();

  // bookmarklet
  $items['bookmark/let'] = array(
    'title' => 'Bookmarklet',
    'page callback' => 'pinboard_bookmarklet_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'pinboard.pages.inc'
  );

  $items['bookmark/let/post'] = array(
    'title' => 'Bookmarklet',
    'page callback' => 'pinboard_bookmarklet_page',
    'page arguments' => array('post'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'pinboard.pages.inc'
  );

  // callbacks
  $items['bookmark/%/%'] = array(
    'title' => 'Bookmark action',
    'page callback' => 'pinboard_actions_page',
    'page arguments' => array(1, 2),
    'access callback' => 'pinboard_access',
    'access arguments' => array('create bookmarks', 'delete own bookmarks'),
    'file' => 'pinboard.pages.inc',
    'type' => MENU_CALLBACK
  );

  $items['bookmark/%/delete'] = array(
    'title' => 'Delete bookmark',
    'page callback' => 'pinboard_delete',
    'page arguments' => array(1),
    'access arguments' => array('delete own bookmarks'),
    'type' => MENU_CALLBACK
  );

  // User-specific data
  $items['user/%user/bookmarks'] = array(
    'title' => t('Bookmarks'),
    'page callback' => 'pinboard_user_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'pinboard.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5
  );

  return $items;
}

/**
 * Implememtation of hook_access
 * Check for multiple permissions
 */
function pinboard_access() {
  foreach(func_get_args() as $perm) {
    if (!user_access($perm)) {
      return FALSE;
    }
  }

  return TRUE;
}

/**
 * Checks for bookmarks page access
 *
 * @param $account
 *    The user account object
 *
 * @return Boolean
 *
 * @see user_view_access()
 */
function pinboard_bookmarks_access($account) {
  $data = unserialize($account->data);
  $public = ($data['pinboard_visibility'] == 'public');

  return $account && $account->uid &&
    (
      // Always let users view their own bookmarks.
      ($GLOBALS['user']->uid == $account->uid) ||
      // Administrators can view all bookmarks.
      user_access('administer users') ||
      // The viewed user is not blocked and logged in at least once.
      // The bookmarks page is public and the viewing user has permission
      ($account->access && $account->status && $public &&
        user_access('view public bookmarks', $GLOBALS['user']) )
    );
}

/**
 * Implementation of hook_user()
 * Inject a private/public bookmarks page option
 *
 * @todo detect login from bookmarklet and do proper redirect.
 */
function pinboard_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'form' && $category == 'account') {
    $data = unserialize($account->data);
    $form['pinboard'] = array(
      '#type' => 'fieldset',
      '#title' => t('Bookmarks')
    );

    $form['pinboard']['pinboard_visibility'] = array(
      '#type' => 'radios',
      '#title' => t('Visibility'),
      '#options' => array(
        'private' => t('Private'),
        'public'  =>t('Public')
      ),
      '#default_value' => isset($data['pinboard_visibility']) ? $data['pinboard_visibility'] : 'private'
    );

    return $form;
  }
  else if ($op == 'login') {
    if (isset($_GET['token'], $_GET['destination'])) {
      // redirect only if the token is correct
      if ($_GET['token'] == md5('pinboard_redirect__'. $_GET['destination'])) {

        // @see drupal_goto()
        if (!defined('MAINTENANCE_MODE') || MAINTENANCE_MODE != 'update') {
          module_invoke_all('exit', $url);
        }

        // Even though session_write_close() is registered as a shutdown function, we
        // need all session data written to the database before redirecting.
        session_write_close();

        header('Location: '. check_url($_GET['destination']), TRUE, 302);
        exit();
      }
    }
  }
}

/**
 * Implementation of hook_theme()
 */
function pinboard_theme($existing, $type, $theme, $path) {
  return array(
    'pinboard_bookmarklet' => array(
      'arguments' => array('user' => NULL),
      'template'  => 'pinboard-bookmarklet',
      'path'      => $path .'/theme',
    ),
    'pinboard_bookmark' => array(
      'arguments' => array('bookmark' => NULL),
      'template'  => 'bookmark',
      'path'      => $path .'/theme',
      'pattern'   => 'bookmark__'
    )
  );
}

/**
 * Implementation of hook_theme_registry_alter()
 * Move pinboard theme path to the top of suggestions
 */
function pinboard_theme_registry_alter(&$registry) {
  $path = drupal_get_path('module', 'pinboard') .'/theme';
  array_unshift($registry['page']['theme paths'], $path);
}

/**
 * Preprocess function for theme('pinboard_bookmarklet');
 */
function template_preprocess_pinboard_bookmarklet(&$vars) {

  // a bit of fallback. Get current user if no user object provided.
  if (!$vars['user']) {
    global $user;
  }
  else {
    $user = $vars['user'];
  }

  $vars['anonymous'] = TRUE;
  $vars['url'] = preg_replace('/http[s]?\:/', '', $GLOBALS['base_url']);

  if ($user->uid) {
    $vars['id'] = $id = base_convert($user->uid, 10, 36);
    $vars['token'] = $token = drupal_get_token("pinboard_user_{$id}");
    $vars['timestamp'] = $timestamp = time();
    $vars['hash'] = base64_encode(hash_hmac('sha256', "pinboard__{$id}__{$token}__{$timestamp}", "pinboard_user_{$token}", TRUE));
    $vars['anonymous'] = FALSE;
  }
}